### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by johnwargo** [rrobinet/Visio-Stencils#1]
I don't see a license file associated with the stencils. Can you add one? If not, can i have permission to use them in a graphic for a magazine article I'm writing?

**Comment by rrobinet** [comment]
John,

No license, and no problem, this is my small contribution to all the infos I can get from Github, so feel free to use it.

Robert
On 09 Oct 2017, at 14:35, John M. Wargo <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see a license file associated with the stencils. Can you add one? If not, can i have permission to use them in a graphic for a magazine article I'm writing?

**Comment by pjb304** [comment]
Hi,

I just came looking for the exact same information, permission to use a template you have generously uploaded in a presentation I'm giving.  

Github is confusing as whilst you can make a repo public but unless a license is explicitly stated "the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work." (https://help.github.com/articles/licensing-a-repository/), which from your above comment is not your intention.  If you are happy for anyone to use the libraries (which are great) then a license like https://choosealicense.com/licenses/cc0-1.0/ might be a good choice. 

Thanks
